### ISSUE TITLE
PyMongo: `skip` and `limit` are ignored by `__getitem__`

### ISSUE THREAD

**Issue by JadonKrys** [dsschult/file_catalog#6]
The `limit` and `skip` parameter of the `Mongo.find_files()` method are ignored because `__getitem__` ignores them, see http://api.mongodb.com/python/current/api/pymongo/cursor.html#pymongo.cursor.Cursor.__getitem__

As the `start` parameter has been implemented as a list slice, it is already supported. However, the `limit` parameter will be **always** ignored.

The fix could be `for row in result[start : start + end]:...`

**Comment by dsschult** [comment]
Works for me, though we should test if this introduces slowness when on page 1000 :smile: 

Not sure there is really a good workaround for high skip values, but maybe they won't happen very often and we can ignore it.

**Comment by JadonKrys** [comment]
I don't see a issue with high skip values since the lists are accessed by index. So, it isn't slower to access `l[10000]` than `l[0]`, right?

**Comment by dsschult** [comment]
it's slower because the list doesn't exist until an item is asked for, so it actually has to go back and ask the DB for each item as it iterates/slices.

**Comment by JadonKrys** [comment]
Ah! Thanks, I didn't know that :)
