### ISSUE TITLE
Add maximum number of results when querying the file list

### ISSUE THREAD

**Issue by JadonKrys** [dsschult/file_catalog#8]
It is currently not any more in the code.

I would suggest adding a config file where one can specify such parameters in order to avoid the need to modify the actual code.

**Comment by dsschult** [comment]
For config files:

1. `ConfigParser`

2. json config.  I like:
    https://github.com/WIPACrepo/iceprod/blob/master/iceprod/server/config.py
    We could break this out into a separate package if you want it.

**Comment by JadonKrys** [comment]
I think we should also add the list of mandatory fields to the config file. Better than hard code it.

**Comment by JadonKrys** [comment]
> json config. I like: https://github.com/WIPACrepo/iceprod/blob/master/iceprod/server/config.py
I don't know if this is too much. Currently, we just have a couple of settings. I guess for now the `ConfigParser` is sufficient?!
